### ISSUE TITLE
DOC Issue: can not find the example `Examples/ios/frameworks/`

### ISSUE THREAD

**Issue by beiliubei** [MyUNiDAYS/Segmenkt#10]
_When issuing a bug report please include as many of the below details as possible. If you find a Closed issue that seems like it is the same thing that you're experiencing, open a new issue and include a link to the original issue in the body of your new one._

### Describe the bug

**To Reproduce**

Steps to reproduce the behaviour:
2. Click on '...'
3. Scroll down to '...'

**Reproduces how often:**

What percentage of the time does it reproduce, if you know?

**Expected behaviour**

**Screenshots**

**Additional context**

**Comment by Reedyuk** [comment]
Ah the readme mentions the frameworks, you will need to build this locally. 
I can adjust the readme to not reference this.
